### ISSUE TITLE
Missing file from latest version NPM package ?

### ISSUE THREAD

**Issue by Tahul** [datocms/vue-datocms#14]
Hello,

I seem to have a problem using "vue-datocms@0.0.8".

When I import the package to my project, it doesn't seem to import the "dist/vue-datocms.umd.js".

As this file is the "main" entry of your package, this results in "This dependency was not found:" error in any project that use your package.

Only the "dist/vue-datocms.min.js" (which doesn't seem to be minified) seem to be uploaded to NPM.

I tried it from my main project, the created simple test project with `npm init` and only installed vue-datocms.

You can find a screenshot of my node_modules with that test project attached to that message.

It is strange because I cloned this library on my laptop, build the files, and used `npm link` to join my main project and this local version of vue-datocms, and everything worked well.

Maybe it was a mistake while publishing on NPM ?

Anyway, could you fix that on a new NPM version ?

Thanks a lot, DatoCMS is a really great service :)

---

<img width="223" alt="Capture d’écran 2020-12-14 à 17 21 17" src="https://user-images.githubusercontent.com/1385263/102106373-c8042800-3e30-11eb-8be1-4223a43ded97.png">

![image](https://user-images.githubusercontent.com/1385263/102106614-144f6800-3e31-11eb-9348-ef3011531b8b.png)

**Comment by stefanoverna** [comment]
Hi @Tahul! Thanks, we just released 0.1.0 which fixes the issue!

**Comment by Tahul** [comment]
Hello @stefanoverna ;

Seems like you updated the package which added "vue-datocms.esm.js" to your "dist/" files.

It's great to add the ESM module but the "main" file of your package is still missing, "vue-datocms.umd.js", which still results in a missing module error when importing your package.

![image](https://user-images.githubusercontent.com/1385263/102510789-4f97a400-4088-11eb-80a9-a9e136866e9b.png)

![image](https://user-images.githubusercontent.com/1385263/102510819-57574880-4088-11eb-8606-01108ddbfcf8.png)

**Comment by stefanoverna** [comment]
This was the cause, damn it :) https://github.com/datocms/vue-datocms/commit/e15d18db91e412c7f5ffd4acb9f130610f32f67d#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

The build wasn't waiting the tasks to complete!

v0.1.3 fixes this for good
